use crate::types::generate_enum;
use std::fs::File;
use std::io::prelude::*;

pub fn generate_header() {
    let mut file = File::create("binapi/generated.rs").unwrap();
    file.write(b"// This file is autogenerated by the API Generator \n")
        .unwrap();
    generate_enum(&mut file);
}
